name: sky_bridge
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  atproto: ^0.5.1
  bluesky: ^0.7.1
  bluesky_text: ^0.2.1
  collection: ^1.17.1
  copy_with_extension: ^5.0.2
  crypto: ^3.0.2
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.8.2
  dcli_core: ^3.0.3
  dotenv: ^4.1.0
  html: ^0.15.3
  json_annotation: ^4.8.0
  orm: ^3.4.4
  path: ^1.8.3
  shelf_cors_headers: ^0.1.5
  shelf_rate_limiter: ^1.0.1
  template_expressions: ^3.0.0+5
  yet_another_json_isolate: ^1.0.4

dev_dependencies:
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.2
  fixnum: ^1.1.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  http: ^0.13.6